// import swagger for API documentation
import swaggerUi from "swagger-ui-express"
import swaggerJsdoc from "swagger-jsdoc"
import { Express, Request, Response } from "express"
import openApiSpec from "./OpenAPI_spec.json"

// Define the options for Swagger documentation
const options: swaggerJsdoc.Options = {
	definition: openApiSpec,
	apis: ["./src/routes/*.ts"], // files containing annotations as above
}

// The Swagger specifications generated by swaggerJsdoc.
const specs = swaggerJsdoc(options)

export default (app: Express, port?: Number) => {
	// Swagger page
	app.use(
		"/api-docs",
		swaggerUi.serve,
		swaggerUi.setup(specs, { explorer: true })
	)

	// Docs in JSON format
	app.get("/api-docs.json", (req: Request, res: Response) => {
		res.setHeader("Content-Type", "application/json")
		res.send(specs)
	})

	// log.info(`Swagger documentation available at http://localhost:${port}/api-docs`)
}
